//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conversation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Conversation()
        {
            this.Repository = new HashSet<Repository>();
        }
    
        public int IdConversation { get; set; }
        public Nullable<int> IdIntersted { get; set; }
        public Nullable<System.DateTime> QuestionDate { get; set; }
        public Nullable<System.DateTime> AnswerDate { get; set; }
        public string Question { get; set; }
        public string Answer { get; set; }
        public Nullable<int> IdEmployee { get; set; }
        public Nullable<int> IdQuestion { get; set; }
        public Nullable<bool> IsToRepository { get; set; }
        public Nullable<int> IdConversationStatus { get; set; }
    
        public virtual ConversationStatus ConversationStatus { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Intersted Intersted { get; set; }
        public virtual Question Question1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Repository> Repository { get; set; }
    }
}
