//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Intersted
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Intersted()
        {
            this.Conversation = new HashSet<Conversation>();
            this.PLogging = new HashSet<PLogging>();
            this.VLogging = new HashSet<VLogging>();
        }
    
        public int IdIntersted { get; set; }
        public string FirstNameIntersted { get; set; }
        public string LastNameIntersted { get; set; }
        public string TzInterested { get; set; }
        public string GmailIntersted { get; set; }
        public string CellInterested { get; set; }
        public Nullable<int> IdResource { get; set; }
        public Nullable<int> IdFaculty { get; set; }
        public Nullable<int> IdDiploma { get; set; }
        public Nullable<int> IdPersonStatus { get; set; }
        public Nullable<int> IdCollege { get; set; }
        public Nullable<int> IdUser { get; set; }
    
        public virtual College College { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Conversation> Conversation { get; set; }
        public virtual Diploma Diploma { get; set; }
        public virtual Faculty Faculty { get; set; }
        public virtual PersonStatus PersonStatus { get; set; }
        public virtual Resource Resource { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PLogging> PLogging { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VLogging> VLogging { get; set; }
    }
}
