//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLogging
    {
        public int IdPLogging { get; set; }
        public Nullable<int> IdPreparatory { get; set; }
        public Nullable<int> IdIntersted { get; set; }
        public string Comment { get; set; }
        public Nullable<bool> IsArrival { get; set; }
    
        public virtual Intersted Intersted { get; set; }
        public virtual Preparatory Preparatory { get; set; }
    }
}
