//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Preparatory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Preparatory()
        {
            this.PLogging = new HashSet<PLogging>();
        }
    
        public int IdPreparatory { get; set; }
        public string NamePreparatory { get; set; }
        public Nullable<int> IdFaculty { get; set; }
        public Nullable<int> IdDiploma { get; set; }
        public Nullable<System.DateTime> BeginDate { get; set; }
        public Nullable<int> NumDays { get; set; }
        public Nullable<int> NumHours { get; set; }
        public string Days { get; set; }
        public Nullable<int> Price { get; set; }
    
        public virtual Diploma Diploma { get; set; }
        public virtual Faculty Faculty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PLogging> PLogging { get; set; }
    }
}
