//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int IdTask { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsDone { get; set; }
        public Nullable<System.DateTime> RemindeTime { get; set; }
    }
}
