//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class VLogging
    {
        public int IdVLogging { get; set; }
        public Nullable<int> IdVisitors_Day { get; set; }
        public Nullable<int> IdIntersted { get; set; }
        public string Comment { get; set; }
        public Nullable<bool> IsArrival { get; set; }
        public Nullable<bool> Reminder { get; set; }
    
        public virtual Intersted Intersted { get; set; }
        public virtual Visitors_Day Visitors_Day { get; set; }
    }
}
